### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by drusellers** [jamesmacaulay/shopify-clj#5]
I don't see any functions around webhooks, is that correct? I think it would need to be added around here https://github.com/jamesmacaulay/shopify-clj/blob/master/src/shopify/resources/routes.clj#L101

Is that correct?

-d

**Comment by jamesmacaulay** [comment]
The code you linked to is special-case code for resources that act a bit differently than most. I believe the Webhook resource thoroughly follows the conventions, so you should be able to make calls like so:

```clojure
(shop/save! :webhook
            {:topic "orders/create"
             :address "http://whatever.hostname.com"
             :format "json"}
            auth)
```

**Comment by drusellers** [comment]
It does and it works. I struggled for awhile because the shopify docs on the webhook topic's is pretty poor. But otherwise the library is working like a champ. Thank you.
